plugins {
    id 'com.android.application'
}

android {
    namespace 'id.aisy.alarmbangun'
    compileSdk 34

    defaultConfig {
        applicationId 'id.aisy.alarmbangun'
        minSdk 26
        targetSdk 33
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    androidResources {
        noCompress 'mp3'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
